system: # Настройки системы
  name: "Dev" # Укажите наименование системы, Пример: staging
  debug: 1 # Режим отладчика (Поумолчанию: 0, Режимы: 0 - Режим отладчика выключен 1 - Расширенное логгирование, 2 - Расширенное логгирование и трассировка )
  logging: # Настройки логгирования
    file_mode: true
    file_mode_settings:
      directory_path: "/tmp/spiderd2" # Укажите папку куда писать логи (абсолютный путь)
      max_size: 50  # Укажите максимальный размер(мб) лог файла 
      max_rotate: 5 # Укажите максимальное количество ротаций лог файла
      gzip: true # Укажите требуется ли архивированние ротациионых лог файлов
    std_mode: true